# Generated by Django 4.1.1 on 2022-10-11 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Face_Detection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('face_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('address', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=20)),
                ('username', models.CharField(default='', max_length=50)),
                ('password', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
