# Generated by Django 4.1.1 on 2022-11-22 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Face_Detection', '0005_alter_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='place',
            field=models.CharField(default='', max_length=30),
        ),
    ]
