# Generated by Django 4.1.1 on 2022-09-28 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidatedb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidateid', models.IntegerField()),
                ('candidatename', models.CharField(max_length=10)),
                ('partyname', models.CharField(max_length=10)),
                ('membersprt', models.IntegerField()),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=30)),
                ('photo', models.ImageField(default='null.jpg', upload_to='Image')),
                ('logo', models.ImageField(default='null.jpg', upload_to='Image')),
            ],
        ),
    ]
