# Generated by Django 4.1.1 on 2022-10-06 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatedb',
            name='vote',
            field=models.IntegerField(default=0),
        ),
    ]
