# Generated by Django 4.1.1 on 2022-10-25 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0002_candidatedb_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatedb',
            name='password',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='candidatedb',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
    ]
