# Generated by Django 4.1.1 on 2022-11-04 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0004_candidatedb_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatedb',
            name='candidatename',
            field=models.CharField(max_length=20),
        ),
    ]
