# Generated by Django 4.1.1 on 2022-11-04 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0005_alter_candidatedb_candidatename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatedb',
            name='partyname',
            field=models.CharField(max_length=20),
        ),
    ]
