# Generated by Django 4.1.1 on 2022-11-04 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0006_alter_candidatedb_partyname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatedb',
            name='password',
            field=models.CharField(default='', max_length=20),
        ),
    ]
