# Generated by Django 3.2.15 on 2022-10-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logindb',
            fields=[
                ('face_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('address', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=20)),
                ('username', models.CharField(default='', max_length=50)),
                ('password', models.CharField(default='', max_length=10)),
                ('date', models.DateField(default='2000-12-02')),
            ],
        ),
        migrations.DeleteModel(
            name='Regisdb',
        ),
    ]
