# Generated by Django 3.2.15 on 2022-10-20 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_auto_20221013_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=30)),
                ('phone', models.IntegerField()),
                ('message', models.TextField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Logindb',
        ),
    ]
